### ISSUE TITLE
TypeError: s is null

### ISSUE THREAD

**Issue by Baklashkaa** [Dantevg/WebStats#102]
I am trying to integrate statistics into my nextjs (react) application. I did everything according to the documentation, and it led me to this code:
```
import WebStats from "@components/WebStats-dist"
import { useEffect } from 'react';

export default function Layout({ children }) {

    useEffect(() => {
        const stats = new WebStats({
            host: "localhost:8080",
            tableParent: document.getElementById("webstats-tables"),
            updateInterval: 10000,
            showSkins: true,
            displayCount: 100,
        })
    }, []);

    return (
        <div>
            <div id="webstats-tables"/>
        </div>
    )
}
```

As a result, the div with id="webstats-tables" returns an error:
`TypeError: s is nullTypeError: s is null`

And the console writes this error:
```
TypeError: s is null
    M WebStats-dist.js:12
    promise callback*M WebStats-dist.js:12
    Layout layout.js:10
    commitHookEffectListMount react-dom.development.js:21102
    commitHookPassiveMountEffects react-dom.development.js:23154
    commitPassiveMountOnFiber react-dom.development.js:23259
    recursivelyTraversePassiveMountEffects react-dom.development.js:23237

    overrideMethod <anonymous code>:1
    error app-index.tsx:25
    error hydration-error-info.ts:72
    catchError WebStats-dist.js:12

    M WebStats-dist.js:12
    Layout layout.js:10
    commitHookEffectListMount react-dom.development.js:21102
    commitHookPassiveMountEffects react-dom.development.js:23154
```

Maybe I did something wrong, I'm asking for help 😔

**Comment by Dantevg** [comment]
Hi! By looking at the code, I think the issue is that the `#webstats-tables` element does not exist yet when you call the `document.getElementById("webstats-tables")` in the WebStats constructor. It's a bit hard to verify because of the js minification though 😅

I'm not 100% sure on how the react stuff works, maybe you create the element before calling the WebStats constructor?

**Comment by Baklashkaa** [comment]
Yes, indeed webStats is called before page generation. 😓
Is there another way to load data into a table?

**Comment by Baklashkaa** [comment]
It really worked! The only thing I'm not sure is, should the table be duplicated?
![изображение](https://github.com/user-attachments/assets/ca885428-396e-4e48-b3cc-2a95ed0ab46e)

**Comment by Dantevg** [comment]
That's not supposed to happen, no. Are you sure the WebStats constructor is not called multiple times? The tables will be duplicated when you call it twice.

**Comment by Baklashkaa** [comment]
Yes, it's true, I completely forgot that useEffect() is called 2 times in react. Thanks a lot for the help!

**Comment by Dantevg** [comment]
I'm glad you got it working! 👍
