### ISSUE TITLE
MySQL Auto Reconnect

### ISSUE THREAD

**Issue by coco0325** [Dantevg/WebStats#14]
The plugin should reconnect automatically after the connection is closed.
https://pastebin.com/eN1LkPM8

**Comment by Dantevg** [comment]
Thanks for opening an issue again! I believe I already fixed this in the not-yet-released version 1.6.
I attached the latest development version which contains the fix: [WebStats-1.5.1-dev3.zip](https://github.com/Dantevg/WebStats/files/7744150/WebStats-1.5.1-dev3.zip)

**Comment by coco0325** [comment]
https://pastebin.com/rV04vJh8
The issue still exists.

**Comment by Dantevg** [comment]
I tried something else, hopefully that fixed it. Latest development version attached again: [WebStats-1.5.1-dev4.zip](https://github.com/Dantevg/WebStats/files/7771263/WebStats-1.5.1-dev4.zip)
(note: not properly tested, it might still not work or there might be other bugs)

**Comment by Dantevg** [comment]
I assume it is fixed now, closing. Please re-open and comment if the bug is still there :)
