### ISSUE TITLE
Placeholders compatibility

### ISSUE THREAD

**Issue by zeus1921** [Dantevg/WebStats#3]
hey

Is it possible to add Placeholders compatibility? for example add faction power to the table, or mcmmo level, by adding %placeholder% to a .yml config

**Comment by Dantevg** [comment]
Hey, thanks for this feature request!

I had never come across the PlaceholderAPI, it seems like an awesome thing that would fit the WebStats plugin perfectly!
It looks to be pretty simple to implement and I think it should be able to work with the existing `objectives` option in `config.yml`. I'll look into it properly soon, probably after I am done with the mysql feature (#2).

**Comment by Dantevg** [comment]
So I implemented support for the PlaceholderAPI in the latest version, I hope this is roughly what you meant? If you feel like something is missing, please let me know!
