### ISSUE TITLE
Sorting Refresh?

### ISSUE THREAD

**Issue by NickMesser** [Dantevg/WebStats#50]
When I apply any filter in the latest build it for some reason like resets the filter and goes back to the default view after just a few moments. I assumed it was the update interval causing it but even after disabling auto updates it still seems to remove the filters on me. 

I am using the default web page you made with the default index/styles. 

Example below. 

s1stats.mineroyalemc.com

**Comment by Dantevg** [comment]
Thanks for the bug report! I've been able to reproduce it and it will be fixed soon.

**Comment by Dantevg** [comment]
Fixed in v1.8.2! Apparently defocussing and refocussing the page also caused a flood of stats updates when they were disabled 😬, that is also fixed now.
