### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by coco0325** [Dantevg/WebStats#57]
Happens when closing WebStats browser tab.

Error: https://pastebin.com/8TsUXPMQ

**Comment by Dantevg** [comment]
Thanks for the bug report again! Sorry it took me so long to look at this.

This seems like an exception that is safe to ignore, so now the exception is no longer logged. I will publish a version with this fix later today :)

**Comment by Dantevg** [comment]
Sorry for the wait, turns out I had some other things to add to this update 🙂
Version 1.8.5 includes this fix and is now available here: https://github.com/Dantevg/WebStats/releases/tag/v1.8.5
