### ISSUE TITLE
Discord webhook does not update

### ISSUE THREAD

**Issue by Olen** [Dantevg/WebStats#79]
Seems like the webhook does not work properly.
I set it to update discord every 10 minute, but it will only send one update on startup, and never again.
If I remove `discord-message-id.txt` and run `webstats restart` it will send another update to Discord, but nothing is sent automatically later.

**Comment by Dantevg** [comment]
I cannot reproduce this. Mind that WebStats sends a single message which is updated every 10 minutes, maybe you were expecting it to send a new message every time? The time of the last update can be seen at the bottom of the message.

**Comment by Olen** [comment]
Ah. Ok. That means that it scrolls out of view if the channel is used for other messages. 
Not a big problem for me. The webstats are good enough. I was just testing it and could not see the updates.

**Comment by Dantevg** [comment]
I figured it would be quite annoying if a channel would be constantly bombarded with update messages. Even every 10 minutes would result in a lot of messages per day. If you have a compelling use-case we could maybe add a toggle in the config to disable reusing the old messages?

**Comment by Olen** [comment]
Totally understand. If I wanted to use it, I would probably add a dedicated channel to solve the "problem".
I was just checking it out

**Comment by Dantevg** [comment]
Alright, thanks for checking it out anyway!
