### ISSUE TITLE
Set icon for Discord Webhook

### ISSUE THREAD

**Issue by Olen** [Dantevg/WebStats#80]
The Wehook will use the default Discord Icon even if another one is set for the webhook in Discord settings.
There should be a way to either specify the icon and name to use or use the one set in the webhook-settings in Discord.

**Comment by Dantevg** [comment]
I only now realised that the icon was set to a URL from an old and deleted branch the entire time (for more than a year)! I'll add an option to not override the name and icon from Discord's settings, good idea!
