### ISSUE TITLE
Custom player names and server row improvements

### ISSUE THREAD

**Issue by sdosker** [Dantevg/WebStats#82]
1)
One thing i find missing on this plugin is a way to edit the player name, but using an ingame value, like "[LV] PlayerName"
Or even something like "Playername [LV]".

Basically a way to append an title or achivement of the players (specially if using PlaceholderAPI)

2)
Another thing i'm not sure if there's a way but i think it should... A way to completely turn off the data gathering from the scoreboard file, i tried those configurations (below) but the `ip:port/stats.json` still populated with data from the scoreboard file...

```
objectives: []
```

```
objectives:
#  - '*'
```

**Comment by Dantevg** [comment]
1. Thanks for the suggestion! Actually I'm surprised nobody suggested that before. I think the best way may be to use one of the placeholder values or scoreboard values for the display name (for instance the `%player_displayname%`). Would that work for you?

2. `objectives: []` should work fine, I just tested. Make sure you either restart the server or run `/webstats reload` when you change the config. An empty `objectives:` does indeed not seem to work, probably that's just how Spigot's yml parser works.

**Comment by sdosker** [comment]
1. Well, maybe... But is it possible to make something just like the placeholders? because i loved how i can configure and use as many placeholder as i want in a single variable.
Something like that:
```
PlayerNameOverride: '[%player_displayname%] %player_gamemode%'
```
I it would show up something like `[Player] Survival`

That way it might be easier to customize later on without relying on other plugins to do the job



2. So, i might have a visual bug?
i'm currently with the config
```
objectives: []
```

but running `/webstats debug` show up this message:
```
[08:41:24 INFO]: WebStats 1.9.1
[08:41:24 INFO]: Active sources: scoreboard, PlaceholderAPI
```
and checking the `ip:port/stats.json` it is still populating the `"scoreboard":{"entries":[ (...)` (i might be wrong, but now it seems like a normal behaviour due the PlaceholderAPI loading)

**Comment by Dantevg** [comment]
1. You can actually already use multiple placeholders in a single column. The following will show an extra column with the player's displayname and gamemode:

   ```yaml
   placeholders:
     '[%player_displayname%] %player_gamemode%': Player
   ```
   I think it'll be an easy solution if WebStats will automatically display a column named "Player" to be the player's name.

2. The `scoreboard` key in the JSON data is actually for all data, including PlaceholderAPI. Its name is a remnant of early versions of WebStats that used to only support the ingame scoreboard. With your config, there should not be any scoreboard objectives present in the JSON, or in the displayed table.

   The fact that the scoreboard source is still loaded when `objectives:` is commented out entirely is a small bug, but that should not matter here.

**Comment by sdosker** [comment]
If making a new column named "Player" replace the default "Player" one, it would be perfect.

I guess the same would work for a Server table, instead of showing up just "Server" we could make up anything with Placeholders...

**Comment by Dantevg** [comment]
I've been thinking about your suggested improvements for server stats. Here's what I will probably do:
- Add a separate `server-name` config item next to `server-columns` where you can use placeholders. This will replace the server's name in the first column (currently "Server").
- Display the server's icon from the server list as the server's "player-head."
- For tables that only display the server's stats and not also player's stats, change the first column's name from "Player" to "Name" (I'm not sure about this one).
- While at it, display the server's status as "online" because it can never be afk or offline.

**Comment by sdosker** [comment]
These improvements seems to be very nice!
Also, if the webpage is hosted somehow apart from the server itself, it is possible for the server to be offline and the page online... But just a too specific and rare possibility...

**Comment by Dantevg** [comment]
That is true, but when the server is offline there won't be a row with stats for the server to display (unless the server went offline while you have the page open :)
