### ISSUE TITLE
Stats not updating

### ISSUE THREAD

**Issue by meistaGG** [Dantevg/WebStats#88]
Hello, 

I have configured both the Spigot plugin on my Minecraft server and the required js, html and css files on my webserver. However, the actual statistics of players are not updating. 

I can tell the IP/port configuration is correct and the webserver is talking to the Minecraft server as the columns I've chosen to display are showing correctly, but no stats are being populated. 

Am I missing something here? 

Thanks!

**Comment by Dantevg** [comment]
Hi, are you sure that the statistic sources you have selected are actually populated? For the scoreboard you can check by displaying the scoreboard objective in the sidebar, for PlaceholderAPI you can check by running `/papi parse me %placeholder%`. If this doesn't show the statistics then that's the problem.

Otherwise, can you upload you config file here? (btw, merry Christmas :)

**Comment by meistaGG** [comment]
Hey, thanks for getting back. 

Running `/papi parse me %placeholder%.` gives only the placeholder as a response, with no statistics/data. 

In any case, I selected Deaths as the only statistic in the column so far and it shows no results, even when I intentionally trigger a player death. I have attached my config file. (GitHub doesn't support native .yml so I have to compress it as a .zip)

[webstats_config.zip](https://github.com/Dantevg/WebStats/files/13766616/webstats_config.zip)

Merry Christmas to you too! 😄

**Comment by Dantevg** [comment]
In the columns you specify which columns should show, not which statistics are actually gathered. That is configured further down in the file, under "objectives" and "placeholders". By default, WebStats will gather all available scoreboard objectives (that's the "*" under objectives). (I'll admit that the config file has become quite confusing/convoluted after adding so many features over the years)

Now, I think you don't have anything installed that gives any statistic. The vanillatweaks datapacks "track statistics" and "track raw statistics" put the Deaths statistic on the scoreboard, along with many more. When you have added those datapacks, WebStats should display the Deaths statistic with your current config. Hope this helps!

**Comment by meistaGG** [comment]
Hey, thanks for clarifying. 

I have installed both datapacks from VanillaTweaks (Track Statistics and Track Raw Statistics) and restarted the server but the page still isn't updating. 

This is the output when I checked what the datapacks were tracking:

![image](https://github.com/Dantevg/WebStats/assets/108792182/87e0b335-9406-41ae-bbd0-fdecf6420d5d)

Could I be missing something? Do I need to set up the datapack further? (I assumed it was plug and play)

Could I also suggest putting a requirement in this wiki to say that these datapacks are a necessary requirement? 😅

**Comment by Dantevg** [comment]
If you display the scoreboard objective on the sidebar (I think it's called `ts_deaths`: `/scoreboard objectives setdisplay sidebar ts_deaths`), does it show the amount of deaths? These datapacks only track statistics starting from the moment they are installed, so you may need to trigger a death :)

Thanks for the suggestion, I will see where I can put this in the wiki (probably multiple pages). These datapacks aren't directly required though. WebStats is just meant to display statistics that are already gathered (and I mean statistics in general, not the ones on the statistics screen in-game). You just need *some* plugin or datapack that provides statistics.

**Comment by meistaGG** [comment]
So I checked in-game and it shows the deaths, but on the web it's still not showing 🤔

**Comment by Dantevg** [comment]
Can you open `ip:port/stats.json` in your browser and see if the stats are present there?

**Comment by meistaGG** [comment]
Hey, 

Server IP right? Nothing is found. :-/

**Comment by Dantevg** [comment]
The same ip and port you entered in `index.html`. If that doesn't return anything there may be an error in the server console.

**Comment by meistaGG** [comment]
There is an output/I can see player names and online players in scoreboard, but there doesn't seem to be any stats present. 
example:
```
{
  "online": {
    "Maarloo": true,
    "Bacenzz": true,
    "ItzRainbowMC": true
  },
  "scoreboard": {
    "entries": [
      "buseton",
      "stikybamboo",
      "MeijoGG",
      "#continue",
      "100000",
      "Dinosymptom",
      "Bacenzz",
      "beugy",
      "Steeno44",
      "ArchydaCookie",
      "buyonly",
      "skils_",
      "Maarloo",
      "0PedroSantos0",
      "AugustForster45",
      "Siga_TBH",
      "Ethanyapl7",
      "#steps",
      "catgifmax",
      "MIGHTBEMEISTA",
      "Djenssen12",
      "Autismo_Veggies",
      "FoxRio",
      "killerpanda993",
      "kyuch",
      "100",
      "_V_O_V_",
      "1200",
      "klevmeister",
      "#doTileDrops",
      "ItzRainbowMC"
    ],
    "columns": [],
    "scores": {}
  },
  "playernames": [
    "MIGHTBEMEISTA"
  ],
  "units": {}
}```

**Comment by Dantevg** [comment]
I really don't know what is going on. It does find a list of players that have scores on the scoreboard, but not the actual scores...

I can't reproduce this behaviour on a new/clean paper `1.20.4-355` server with WebStats `1.10.0`, maybe you're running a weird server version or some other plugin is messing with it?
