### ISSUE TITLE
Setting up the .html and config help

### ISSUE THREAD

**Issue by mrboog12** [Dantevg/WebStats#9]
Hi, I am trying to understand how to setup this exactly,

The help to setup isnt easy for me to understand (Prolly just me), but I cant seem to understand how to add in multiple columns and link them to their correct placeholder/scoreboard objective.

And as for a webpage, I do not quite understand how to set it up correctly :/

Is there an example of any of these that can help me understand it all better?

**Comment by Dantevg** [comment]
Hi!

I think you're talking about the `columns` field in `config.yml`. That is just for the displayed columns on the web page. Tou don't *need* to use it, it is only for overriding the default alphabetical sorting. If you leave it commented out (default), it will display all columns you specified with `objectives`, `database.config` and `placeholders`.

Now, if you *do* want to order the columns differently, the columns are identified ("linked") by name, so for scoreboard objectives that will be their display name, and for placeholders that will be what you named them. So for example you could have:
```yaml
columns: [Mine Diamond, Biome, Deaths]

objectives:
  - Deaths
  - Mine Diamond

placeholders:
  '%player_biome%': Biome
```

For the webpage, there is an example html file in [`web/example/index.html`](https://github.com/Dantevg/WebStats/blob/master/web/example/index.html). You can see that in action [here](https://dantevg.nl/mods-plugins/WebStats/demo/) (I keep forgetting to link to that demo from the readme)

Hope this helps you, let me know if you can get it working!
