### ISSUE TITLE
disabling skins breaks the website

### ISSUE THREAD

**Issue by bacalhau-seco** [Dantevg/WebStats#95]
im not sure how to explain this, so i will send an image.
when setting `showSkins: false` in the html the whole player name tab apears as "false" and the whole stats get pushed to the side.
`showSkins: false`
![image](https://github.com/Dantevg/WebStats/assets/64091315/7087c60f-86c4-473f-b322-bdba112b86da)

`showSkins: true`
![image](https://github.com/Dantevg/WebStats/assets/64091315/ada45731-55b6-4542-8fc3-059ad926d15f)

**Comment by Dantevg** [comment]
That's what I get for not testing things... Was an easy fix, can be downloaded here: https://github.com/Dantevg/WebStats/actions/runs/9386932725/artifacts/1571605579.

Thanks for the bug report!

**Comment by bacalhau-seco** [comment]
thank you again
