### ISSUE TITLE
https issue

### ISSUE THREAD

**Issue by bacalhau-seco** [Dantevg/WebStats#96]
I just realized now, but no one in my server could actually see the stats as it would fail to make an https connection.
So i checked the [https guide](https://github.com/Dantevg/WebStats/wiki/HTTPS) and set up the reverse proxy and that thing on the html, and i had issues with it.
The first one i think i might have fixed, but basically there was an error saying `Uncaught ReferenceError: Connection is not defined`. I actually fixed this one by adding `import Connection from "./WebStats-dist.js"`  bellow the import webstats.
After that i tried loading the page again but now it seems to have an error with the javascript, im not sure. this is the error:
`Uncaught TypeError: e is undefined`
Im not sure what the issue is, im on Librewolf, and [this is the website](https://basedmc.club/stats/)

**Comment by Dantevg** [comment]
It seems that the wiki is outdated. A while back I added the possibility to specify `https` in the main constructor. You can simply specify `host: "https://basedmc.club"` in the main WebStats constructor (and remove the `connection: new Connection({...})` lines), no need to import Connection anymore 🙂

**Comment by bacalhau-seco** [comment]
ye i did exactly that, it works now.
However, you also need to reverse proxy tables.json.

Simply add this to the nginx config:
`location /tables.json {`
`proxy_pass http://ip:port/tables.json;`
`}`

thanks for the help, everything should word now
