### ISSUE TITLE
Citizens NPCs listed in Webstats

### ISSUE THREAD

**Issue by kommodore1024** [Dantevg/WebStats#99]
We have some Citizens NPCs listed in Webstats. Is there a way to filter out all the players (NPCs) that don't have any statistics?

**Comment by kommodore1024** [comment]
join_game would be a good stat to use as it only applies to real players.

**Comment by kommodore1024** [comment]
Sure thing! It is here: https://keegcraft.neocities.org/
Click "Server Stats"

it would also be cool if I could remove players that we have previously banned.

**Comment by Dantevg** [comment]
Which of these players are Citizen NPCs? Every player has at least one score on the table, almost every one has a score for Walk. Do the NPCs have scores for Walk too?

As for removing players data, if they have scores on the scoreboard you can remove the scores with `/scoreboard players reset <player>`.

**Comment by kommodore1024** [comment]
It looks like walk is indeed the stat that is making Citizen NPCs appear. I'll remove that stat. Thanks!
